Allow specifiying peer x.509 certificates

diff --git a/run-proxy b/run-proxy
--- a/run-proxy
+++ b/run-proxy
@@ -8,11 +8,16 @@ Arguments:
   --proxy-pass URL                   sets the url to proxy to
   --user USER                        sets the name of the authorized user (default: kube-prometheus:scraper)
   --location URI                     sets the uri for the location (default: /metrics)
+  --proxy-ssl-ca-file path           specify path to CA file in PEM format used to verify peer certificate,
+                                     implies "proxy_ssl_verify on;"
+  --proxy-ssl-cert-file path         specify path to cert file in PEM format used to authenticate to peer
+  --proxy-ssl-key-file path          specify path to key file in PEM format used to authenticate to peer
   -h, --help                         output this message
 EOF
 )
 
-if ! temp=$(getopt -o h --long listen:,proxy-pass:,user:,location:,help -n 'run-proxy' -- "$@") ; then
+if ! temp=$(getopt -o h --long "listen:,proxy-pass:,user:,location:,help,proxy-ssl-ca-file:,
+            proxy-ssl-cert-file:,proxy-ssl-key-file:" -n 'run-proxy' -- "$@") ; then
   >&2 echo
   >&2 echo "$HELP_STRING"
   exit 1
@@ -33,6 +38,12 @@ while true; do
       USER=$2; shift 2;;
     --location )
       LOCATION=$2; shift 2;;
+    --proxy-ssl-ca-file )
+      PROXY_SSL_CA=$2; shift 2;;
+    --proxy-ssl-cert-file )
+      PROXY_SSL_CERT=$2; shift 2;;
+    --proxy-ssl-key-file )
+      PROXY_SSL_KEY=$2; shift 2;;
     -h | --help )
       echo "$HELP_STRING"; exit 0 ;;
     -- )
@@ -54,6 +65,36 @@ if [[ -z $PROXY_PASS ]] ; then
   >&2 echo
   >&2 echo "$HELP_STRING"
   exit 1
+fi
+
+if [ -n "$PROXY_SSL_CA" ]; then
+  PROXY_SSL_VERIFY="$(cat <<EOF | sed 's/^ */      /g'
+    proxy_ssl_verify yes;
+    proxy_ssl_trusted_certificate $PROXY_SSL_CA;
+EOF
+  )"
+fi
+
+if [ -n "$PROXY_SSL_KEY" ] || [ -n "$PROXY_SSL_CERT" ]; then
+  if [ -z "$PROXY_SSL_KEY" ] ; then
+    >&2 echo "--proxy-ssl-key-file is required when --proxy-ssl-cert-file is specified"
+    >&2 echo
+    >&2 echo "$HELP_STRING"
+    exit 1
+  fi
+
+  if [ -z "$PROXY_SSL_CERT" ] ; then
+    >&2 echo "--proxy-ssl-cert-file is required when --proxy-ssl-key-file is specified"
+    >&2 echo
+    >&2 echo "$HELP_STRING"
+    exit 1
+  fi
+
+  PROXY_SSL_CONFIG="$(cat <<EOF | sed 's/^ */      /g'
+    proxy_ssl_certificate_key $PROXY_SSL_KEY;
+    proxy_ssl_certificate $PROXY_SSL_CERT;
+EOF
+  )"
 fi
 
 cat > /etc/nginx/nginx.conf <<EOF
@@ -92,6 +133,8 @@ http {
       }
 
       proxy_pass ${PROXY_PASS};
+${PROXY_SSL_CONFIG}
+${PROXY_SSL_VERIFY}
     }
   }
 }
